### ISSUE TITLE
keybin ctrl + r no work

### ISSUE THREAD

**Issue by ericcobblepot** [OTAcademy/otclientv8#27]
keybin ctrl + r no work
and duplicate : 

```
  1- Keybind.new("Movement", "Mount/dismount", "Ctrl+R", "")
  ----------------
  2-Keybind.new("Dialogs", "Open Rule Violation", "Ctrl+R", "")
```
  
"`\modules\game_ruleviolation\ruleviolation.lua`"
3- `g_keyboard.bindKeyDown('Ctrl+Y', function() modules.game_ruleviolation.show() end)`

**Comment by Oen44** [comment]
`game_playermount` and `game_console` modules are initialized when client launches, meaning:
1. Game features are not loaded
2. Client protocol version is not set
Got the fix ready for these. They will still be duplicate, if you are using old protocol with mounts feature then it is up to you to resolve any conflicts.

As for `game_ruleviolation` then it seems that the issue is server side for not sending some data so it doesn't open.

**Comment by ericcobblepot** [comment]
21c8a8b
